sonar.projectKey=desafio-todo-list
sonar.projectName=DESAFIO-TODO-LIST
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=infra/apis/backend/src,infra/apis/frontend/src
sonar.tests=infra/apis/backend/tests,infra/apis/frontend/tests
sonar.test.inclusions=/test.js,/test.jsx,/test.ts,/test.tsx

sonar.javascript.lcov.reportPaths=infra/apis/frontend/coverage/lcov.info
sonar.exclusions=/node_modules/,/dist/,/coverage/,infra/terraform/,infra/kubernetes/