apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: postgres-primary
  namespace: devops-project

spec:
  serviceName: postgres-primary

  replicas: 1

  selector:
    matchLabels:
      app: postgres-primary

  template:
    metadata:
      labels:
        app: postgres-primary

    spec:
      securityContext:
        fsGroup: 1001
      initContainers:
        - name: fix-permissions
          image: busybox:latest
          command: ["sh", "-c", "chown -R 1001:1001 /bitnami/postgresql"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: postgres-storage
              mountPath: /bitnami/postgresql
      containers:
        - name: postgres
          image: bitnami/postgresql:latest

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRESQL_DATABASE
              value: todolistdb

            - name: POSTGRESQL_USERNAME
              value: postgres

            - name: POSTGRESQL_PASSWORD
              value: "123456"

            # Replicação streaming — papel: primary (escrita)
            - name: POSTGRESQL_REPLICATION_MODE
              value: master

            - name: POSTGRESQL_REPLICATION_USER
              value: replicator

            - name: POSTGRESQL_REPLICATION_PASSWORD
              value: "replicatorpass"

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "todolistdb"]
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5

          volumeMounts:
            - name: postgres-storage
              mountPath: /bitnami/postgresql

  volumeClaimTemplates:
    - metadata:
        name: postgres-storage

      spec:
        storageClassName: standard

        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 2Gi