server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Proxy para a API backend
    location /tasks {
        proxy_pass http://api-backend:3000/tasks;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /task {
        proxy_pass http://api-backend:3000/task;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
